### ISSUE TITLE
Tenants and Subscription Name and ID is null after login to AzureChinaCloud

### ISSUE THREAD

**Issue by lucyger** [Azure/migAz#68] opened 2017-06-26 09:33 UTC
MigAz couldn't find tenant info since version2. MigAz 1.5 could find them.

**Comment by lucyger** [comment] 2017-08-02 07:31
v2.2.12 reports below error:
AADSTS50001: The application named https://graph.windows.net/ was not found in the tenant named b877a6dc-a4b2-42d4-ae00-520b0a27173a.  This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant.  You might have sent your authentication request to the wrong tenant.
Trace ID: c22adf3c-9c97-45ec-abbd-3acd31d10d00
Correlation ID: 078ce7e6-a23f-401a-b0f0-f499bb760889
Timestamp: 2017-08-02 07:26:32Z
   在 Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenInteractiveHandler.VerifyAuthorizationResult()
   在 Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenInteractiveHandler.<PreTokenRequest>d__8.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   在 Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<RunAsync>d__55.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenCommonAsync>d__54.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenAsync>d__45.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 MigAz.Azure.AzureTokenProvider.<GetGraphToken>d__14.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 MigAz.Azure.AzureRetriever.<GetAzureARMResources>d__78.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 MigAz.Azure.AzureRetriever.<GetAzureARMDomains>d__50.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 MigAz.Azure.AzureTenant.<InitializeChildren>d__16.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 MigAz.Azure.AzureRetriever.<GetAzureARMTenants>d__49.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 MigAz.Azure.UserControls.AzureArmLoginControl.<btnAuthenticate_Click>d__5.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by rsanderson2350** [comment] 2017-08-02 18:56
I have updated the URL for China from https://graph.windows.net/ to https://graph.chinacloudapi.cn/, per documentation at https://msdn.microsoft.com/en-us/library/azure/dn578439.aspx.  Please advise if the issue is resolved or not as of version 2.2.13.0.  I do not have access to a China subscription and unable to personally test.  Merge should occur shortly, will advise soon when merged.

**Comment by rsanderson2350** [comment] 2017-08-13 15:48
@lucyger Have you had an opportunity to validate if the latest version (v2.2.13.0) resolves this issue when connecting to an Azure China subscription?

**Comment by rsanderson2350** [comment] 2018-01-06 17:44
Closing issue based on v2.2.13.0 released which included a change to the Environment URLs for AzureChinaCloud.  This issue is believed resolved.  In the event anyone encounters this again, please open a new issue so we can validate any further resolution need.

**Closed by rsanderson2350** 2018-01-06 17:44 UTC
