### ISSUE TITLE
BUSY: Getting Virtual Network Gateway Shared Key: ExpressRoute

### ISSUE THREAD

**Issue by danieletten** [Azure/migAz#16] opened 2017-03-28 06:58 UTC
When there is an ExpressRoute deployed in the subscription MigAz keeps hanging at "BUSY: Getting Virtual Network Gateway Shared Key: ExpressRoute".

Version 1.4.9.0 doesn't have this issue.
Azure Powershell commands are up to date and the latest version of .NET is installed.

**Comment by PauloRamosGit** [comment] 2017-03-31 14:11
Hi Daniel,
Thank you for reporting the issue. To help us investigate it can you please send the logs files (C:\Users\<user>\AppData\local\MigAz\*.log) to support@migaz.tools?
Regards

**Comment by PauloRamosGit** [comment] 2017-04-03 13:53
Thank you for the logs. We will get back here as soon as the problem is fixed.

**Comment by rsanderson2350** [comment] 2017-04-09 04:20
MigAz v2.0.0.0 (which currently includes the next major update) should be released live within the next day.  Although I don't have access to a subscription with an ASM Classic ExpressRoute VNet, I believe this issues has been fixed by ensuring error handling was added for attempting to get the VNET Gateway key.  Thanks.

**Comment by rsanderson2350** [comment] 2017-04-09 16:49
MigAz ASM to ARM v2.0.0.0 is now available - https://github.com/Azure/migAz/tree/master/release

**Comment by PauloRamosGit** [comment] 2017-04-18 10:37
Hi @danieletten , can you confirm if v2.0.0.0 solved this issue?

**Comment by rsanderson2350** [comment] 2017-04-20 13:58
@danieletten Version 2.1.0.0 is now available. Please validate resolution against the latest version and advise if an issue is still occurring when retrieving Virtual Machine / Compute resources. Thanks.

**Comment by PauloRamosGit** [comment] 2017-05-05 16:39
Hi @danieletten , we will temporary close this issue since this should be already solved on the latest release. Let us know if that is not the case

**Closed by PauloRamosGit** 2017-05-05 16:39 UTC
