### ISSUE TITLE
Can't select the Resource Group location

### ISSUE THREAD

**Issue by BorisChomette** [Azure/migAz#141] opened 2018-03-02 10:13 UTC
With MigAz version 2.4.0.1. While setting up the creation for a new Resource Group, I'm unable to select a location. Instead it shows Set Migration Target Context
This only happens when I choose a different subscription as a target.

**Comment by rsanderson2350** [comment] 2018-03-02 14:46
I believe you give me the exact indicator I needed -- only happens when choosing a different subscription as a target.  The location of the call to load initial subscription details (Providers, Locations and VM Sizes) was refactored.  The issue is likely the need to add this call to the different subscription selected on the target side.  I will do some testing and look to have a fix in a couple of hours.  Thanks.

**Comment by rsanderson2350** [comment] 2018-03-16 10:19
Resolved with v2.4.1.0

**Closed by rsanderson2350** 2018-03-16 10:19 UTC
