### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by scottlotus** [Azure/migAz#65] opened 2017-06-15 14:15 UTC
1. Downloaded latest build from:
https://github.com/Azure/migAz/archive/master.zip

2. Unziped MigAz v2.2.9.0

3. Executed MigAz.exe (Run as Administrator)

4. Selected NEW MIGRATION ASM TO ARM

5. Environment = Azure Cloud.

6. Logged in as subscription admin successfully

7. Selected TENANT.

8. Selected SUBSCRIPTION

APPLICATION REPORTS BUSY:
vnet ok
storage ok
VM cloud service for vm1 (running)
VM cloud service for vm2 (running)
VM cloud service for vm3 (deallocated)

9. On the third VM the following exception is reported:
Object reference not set to an instance of an object.
   at MigAz.Migrators.AsmToArm.<BindAsmResources>d__82.MoveNext()

10. In response I deleted the deallocated VM3.

11. Running  the above process again I now get the same exception on cloud service for VM2.

ThanksObject reference not set to an instance of an object.
   at MigAz.Migrators.AsmToArm.<BindAsmResources>d__82.MoveNext()

Thanks for any help.
Scott

**Environment**

> Windows 10

> VS 2015

> Powershell
$PSVersionTable.PSVersion
Major  5 
Minor  1
Build  14393 
Revision 1198

**Comment by rsanderson2350** [comment] 2017-06-15 17:24
@scottlotus Can you provide a bit more detail from the logs?  Specifically, the full call stack and error line numbers surrounding the Object reference not set to an instance of an object error?

**Comment by scottlotus** [comment] 2017-06-16 06:23
@rsanderson2350 , very sorry I should have provided the LOG information in the first post, did not notice it was available.

16/06/2017 07:14:03   GetAzureASMResources  Start REST Request
16/06/2017 07:14:03   GetAzureRestResponse  00000000-0000-0000-0000-000000001202 Url: https://management.core.windows.net/00000000-0000-0000-0000-000000008439/services/hostedservices/bk1/deployments/bk1/roles/m2mbk1
16/06/2017 07:14:03   GetAzureRestResponse  00000000-0000-0000-0000-000000001202 GET https://management.core.windows.net/00000000-0000-0000-0000-000000008439/services/hostedservices/bk1/deployments/bk1/roles/m2mbk1
16/06/2017 07:14:03   GetAzureRestResponse  00000000-0000-0000-0000-000000001202 Received REST Response
16/06/2017 07:14:03   GetAzureRestResponse  00000000-0000-0000-0000-000000001202 Received REST Response
16/06/2017 07:14:03   GetAzureRestResponse  00000000-0000-0000-0000-000000001202  Status Code OK
16/06/2017 07:14:03   GetAzureRestResponse  00000000-0000-0000-0000-000000001202 End REST Request
16/06/2017 07:14:03   GetAzureAsmStorageAccount  Start
16/06/2017 07:14:03   GetAzureAsmStorageAccounts  Start
16/06/2017 07:14:03   GetAzureAsmStorageAccount  Start
16/06/2017 07:14:03   GetAzureAsmStorageAccounts  Start
16/06/2017 07:14:03   GetAzureAsmStorageAccount  Start
16/06/2017 07:14:03   GetAzureAsmStorageAccounts  Start
16/06/2017 07:14:03   GetAzureAsmStorageAccount  Start
16/06/2017 07:14:03   GetAzureAsmStorageAccounts  Start
16/06/2017 07:14:03   GetAzureAsmReservedIPs  Start
16/06/2017 07:14:03   UnhandledExceptionDialog  Object reference not set to an instance of an object.
   at MigAz.Migrators.AsmToArm.<BindAsmResources>d__82.MoveNext()

Azure SDK 2.9
Will install the 2.9.6 updates.

**Comment by rsanderson2350** [comment] 2017-06-26 16:38
@scottlotus Could you please download the latest published version (v2.2.11.0) and advise if the issue is resolved or still occurring?  I didn't have an exact line number from your last post, but I did try to review those code sections for what the cause could be.  If still occurring, an exact line number (full call stack below that "UnhandledExceptionDialog Object reference not set to an instance of an object" would help.  Thanks.

**Comment by flaviojr0402** [comment] 2017-06-28 13:12
Hello good day! I'm with the same problem, any solution?
Thank you!

**Comment by rsanderson2350** [comment] 2017-07-04 16:16
@flaviojr0402 can you provide the error from your Log file?  Specifically, I'm looking for more details on the line number in which the error is occurring.  I see from the logs provided by another user above the error occurring on a MoveNext() call, but I'm looking for further details in the log from below that "UnhandledExceptionDialog" which should contain more details about the application call stack.

**Comment by flaviojr0402** [comment] 2017-07-05 14:44
@rsanderson2350 

Referência de objeto não definida para uma instância de um objeto.
   em MigAz.Azure.AzureRetriever.<BindAsmResources>d__78.MoveNext()
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em MigAz.Migrators.AsmToArm.<BindAsmResources>d__62.MoveNext()
_______________________________________________________________________________________________________________

5/07/2017 11:42:45   UnhandledExceptionDialog  Referência de objeto não definida para uma instância de um objeto.
   em MigAz.Azure.AzureRetriever.<BindAsmResources>d__78.MoveNext()
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em MigAz.Migrators.AsmToArm.<BindAsmResources>d__62.MoveNext()

**Comment by flaviojr0402** [comment] 2017-07-27 17:32
Referência de objeto não definida para uma instância de um objeto.
   em MigAz.Azure.Asm.LoadBalancerRule.get_ProbePort()
   em MigAz.Azure.Generator.AsmToArm.AsmToArmGenerator.BuildLoadBalancerObject(CloudService asmCloudService, VirtualMachine asmVirtualMachine, ExportArtifacts artifacts)
   em MigAz.Azure.Generator.AsmToArm.AsmToArmGenerator.<UpdateArtifacts>d__9.MoveNext()
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   em MigAz.UserControls.Migrators.AsmToArm.<treeASM_AfterCheck>d__39.MoveNext()
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by rsanderson2350** [comment] 2018-01-06 20:31
Closing.  Original issue identified resolved in v2.2.11.0.  Secondary issue is a duplicate issue posting also posted to #76 and #79.

**Closed by rsanderson2350** 2018-01-06 20:31 UTC
