### ISSUE TITLE
Object reference not set to an instance of an object. in MigAz.Azure.ExportArtifacts when viewing target properties

### ISSUE THREAD

**Issue by DBrownStratiform** [Azure/migAz#208] opened 2018-09-07 17:37 UTC
When trying to migrate a disk, if I change the destination type from "Managed Disk" to "Existing Storage", I receive this error:

Object reference not set to an instance of an object.
   at MigAz.Azure.ExportArtifacts.<ValidateAzureResources>d__61.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\ExportArtifacts.cs:line 371
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.UserControls.TargetTreeView.<RefreshExportArtifacts>d__56.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\UserControls\TargetTreeView.cs:line 230
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Forms.MigAzForm.<PropertyPanel1_PropertyChanged>d__27.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz\Forms\MigAzForm.cs:line 203
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.UserControls.PropertyPanel.<cmbApiVersions_SelectedIndexChanged>d__33.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\UserControls\PropertyPanel.cs:line 283
--- End of stack trace from previous location where exception was thrown ---

**Comment by ruandersMSFT** [comment] 2018-09-08 00:18
Unable to reproduce by selecting a Managed Disk VM and changing disks to Existing Storage / selecting existing ARM Storage Accounts as the target.  Also unclear how line 371 is throwing an Object reference, as all virtualMachine, virtualMachine.TargetSize and this.ResourceGroup.TargetLocation have already been asserted as not null.  There is an Object reference error that existing just below on line 375, wonder if that is the actual line you are experiencing.  Will release a build with that ASAP for validation.

**Comment by ruandersMSFT** [comment] 2018-09-18 17:34
@DBrownStratiform  v2.4.4.1 has been released.  Can you advise if this is still occurring?  If so, please provide updated error message and line number.

**Comment by DBrownStratiform** [comment] 2018-09-18 18:43
Hello,

I am still able to reproduce the issue in v2.4.4.1. It appears to be intermittent though. I can reproduce it when trying to migrate certain ARM VMs. As soon as I click on the Disk Resource in the target window, the error message appears.

[cid:image002.png@01D44F4D.3F962E70]

Here is the full error text:

Object reference not set to an instance of an object.
   at MigAz.Azure.ExportArtifacts.<ValidateAzureResources>d__61.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\ExportArtifacts.cs:line 500
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.UserControls.TargetTreeView.<RefreshExportArtifacts>d__56.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\UserControls\TargetTreeView.cs:line 230
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Forms.MigAzForm.<PropertyPanel1_PropertyChanged>d__27.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz\Forms\MigAzForm.cs:line 203
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MigAz.Azure.UserControls.PropertyPanel.<cmbApiVersions_SelectedIndexChanged>d__33.MoveNext() in C:\Users\ruanders\Source\Repos\migAz\MigAz.Azure\UserControls\PropertyPanel.cs:line 284
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)


Thank you!

**Comment by ruandersMSFT** [comment] 2018-09-19 19:44
Puzzling.  The error now reports line 500 in ExportArtifact.cs, which adds an alert for a VM Data Disk having an invalid LUN Assignment.  That line only references the dataDisk object, which has already been verified to be not up from previous lines.

**Comment by ruandersMSFT** [comment] 2018-09-20 20:33
@DBrownStratiform Please email me at my githubusernameWithoutMSFT@microsoft.com

**Comment by ruandersMSFT** [comment] 2018-11-27 14:30
Merged, released v2.4.4.2

**Closed by ruandersMSFT** 2018-11-27 14:30 UTC
Labels: ReleaseReady
